server:
  port: 9090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: front-end
          uri: http://localhost:8081
          predicates:
            - Path=/boardms/**
        - id: webclient
          uri: http://localhost:8080
          predicates:
            - Path=/board/**
